package com.autoscout24.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.autoscout24.domain.validation.IsFuelTypeSupported;
import com.autoscout24.domain.validation.IsValidUsedCarAdvert;
import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.NotNull;
import java.time.LocalDate;

@DynamoDBDocument
@DynamoDBTable(tableName = "Advert")
@IsValidUsedCarAdvert
public class Advert {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @NotNull
    private String title;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    @IsFuelTypeSupported
    private String fuel;

    @DynamoDBAttribute
    @NotNull
    private Integer price;

    @DynamoDBAttribute
    @NotNull
    private Boolean isNew;

    @DynamoDBAttribute
    private int mileage;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate firstRegistration;

    public Advert(){

    }

    public Advert(String title, String fuel, int price, boolean isNew, int mileage, LocalDate firstReg) {

        this.title = title;
        this.fuel = fuel;
        this.price = price;
        this.isNew = isNew;
        this.mileage = mileage;
        this.firstRegistration = firstReg;
    }

    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getFuel() {
        return fuel;
    }

    public Integer getPrice() {
        return price;
    }

    public Boolean isNew() {
        return isNew;
    }

    public int getMileage() {
        return mileage;
    }

    public LocalDate getFirstRegistration() {
        return firstRegistration;
    }


    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setFuel(String fuel) {
        this.fuel = fuel;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    public void setNew(Boolean aNew) {
        isNew = aNew;
    }

    public void setMileage(int mileage) {
        this.mileage = mileage;
    }

    public void setFirstRegistration(LocalDate firstRegistration) {
        this.firstRegistration = firstRegistration;
    }
}
