package com.autoscout24.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;

import java.time.LocalDate;

@DynamoDBDocument
@DynamoDBTable(tableName = "Advert")
public class Advert {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute
    private String fuel;
    @DynamoDBAttribute
    private int price;
    @DynamoDBAttribute
    private boolean isNew;
    @DynamoDBAttribute
    private int mileage;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate firstReg;

    public Advert(){

    }

    public Advert(String title, String fuel, int price, boolean isNew, int mileage, LocalDate firstReg) {

        this.title = title;
        this.fuel = fuel;
        this.price = price;
        this.isNew = isNew;
        this.mileage = mileage;
        this.firstReg = firstReg;
    }

    public String getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getFuel() {
        return fuel;
    }

    public int getPrice() {
        return price;
    }

    public boolean isNew() {
        return isNew;
    }

    public int getMileage() {
        return mileage;
    }

    public LocalDate getFirstReg() {
        return firstReg;
    }


    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setFuel(String fuel) {
        this.fuel = fuel;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public void setNew(boolean aNew) {
        isNew = aNew;
    }

    public void setMileage(int mileage) {
        this.mileage = mileage;
    }

    public void setFirstReg(LocalDate firstReg) {
        this.firstReg = firstReg;
    }
}
